#!/usr/bin/env yaml
# -*- coding: utf-8 -*-
# =============================================================================
# Created By  : Peem Srinikorn
# Created Date: Tue Sep  8 20:57:59 +07 2020
# =============================================================================

steps:
# This step runs the unit tests on the app
# - name: 'python:3.11'
#   id: Test
#   entrypoint: /bin/sh
#   args:
#   - -c
#   - 'pip install -r requirements.txt && pytest -v'

# This step builds the container image.

- name: 'gcr.io/cloud-builders/docker'
  id: Build
  args:
  - 'build'
  - '-t'
  - 'gcr.io/$PROJECT_ID/$REPO_NAME:$BRANCH_NAME-$SHORT_SHA'
  - '.'

# This step pushes the image to Container Registry

- name: 'gcr.io/cloud-builders/docker'
  id: Push
  args:
  - 'push'
  - 'gcr.io/$PROJECT_ID/$REPO_NAME:$BRANCH_NAME-$SHORT_SHA'

# Deploy image to Cloud Run Google Cloud (asia-southeast1 )
- name: 'gcr.io/cloud-builders/gcloud'
  id : Deploy to Cloud Run
  args:
  # - 'run'
  # - 'deploy'
  # - 'langserve'
  # - '--image'
  # - 'gcr.io/$PROJECT_ID/$REPO_NAME:$BRANCH_NAME-$SHORT_SHA'
  # - '--region'
  # - us-central1
  # - '--platform'
  # - 'managed'
  # - '--allow-unauthenticated'
  - 'run'
  - 'deploy'
  - '${_SERVICE}'
  - '--source'
  - '.'
  - '--port'
  - '8080'
  - '--project'
  - '${PROJECT_ID}'
  - '--allow-unauthenticated'
  - '--region'
  - '${_REGION}'
  - '--set-env-vars'
  - 'OPENAI_API_KEY=${_OPENAI_API_KEY}'

options:
  logging: CLOUD_LOGGING_ONLY

substitutions:
  _SERVICE: langserve
  _REGION: us-central1
  _OPENAI_API_KEY: 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